import os
from fpdf import FPDF
from datetime import datetime
from utils.logger import get_logger

logger = get_logger("PDFGenerator")

class ArecaReportPDF(FPDF):
    def header(self):
        self.set_font('helvetica', 'B', 16)
        self.set_text_color(46, 117, 89)  # Forest Green theme
        self.cell(0, 10, 'ArecaVision AI - Disease Diagnosis Report', border=False, align='C')
        self.ln(12)
        
        # Horizontal rule
        self.set_draw_color(46, 117, 89)
        self.set_line_width(0.8)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by ArecaVision AI Agricultural Decision-Support System', align='C')

def generate_pdf_report(dest_path, farmer_name, original_img_path, gradcam_img_path,
                        predicted_disease, confidence, processing_time, model_used,
                        rec_details, severity_info=None):
    """
    Generates a professional PDF report detailing areca nut disease diagnosis.
    
    Args:
        dest_path: File path to save the generated PDF.
        farmer_name: Name of the farmer/owner (optional).
        original_img_path: Path to the uploaded image.
        gradcam_img_path: Path to the generated Grad-CAM heatmap/overlay image.
        predicted_disease: Class name of the predicted disease.
        confidence: Prediction confidence score (float, e.g. 0.923).
        processing_time: Image processing time in seconds.
        model_used: Deep learning model architecture.
        rec_details: Dictionary containing recommendation engine details.
        severity_info: Optional dictionary from estimate_disease_severity.
    """
    logger.info(f"Generating PDF report at {dest_path}...")
    
    # Initialize PDF
    pdf = ArecaReportPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Metadata / Farmer Details Section
    pdf.set_font('helvetica', 'B', 11)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(40, 6, "Farmer Name:")
    pdf.set_font('helvetica', '', 11)
    pdf.cell(60, 6, farmer_name if farmer_name else "N/A")
    
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(40, 6, "Diagnosis Date:")
    pdf.set_font('helvetica', '', 11)
    pdf.cell(50, 6, datetime.now().strftime("%Y-%m-%d %H:%M:%S"), new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(40, 6, "Classifier Model:")
    pdf.set_font('helvetica', '', 11)
    pdf.cell(60, 6, model_used)
    
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(40, 6, "Processing Time:")
    pdf.set_font('helvetica', '', 11)
    pdf.cell(50, 6, f"{processing_time:.3f} seconds", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    
    # Diagnosis Result Callout Box
    pdf.set_fill_color(240, 248, 245)  # Soft green fill
    pdf.set_draw_color(46, 117, 89)
    pdf.set_line_width(0.5)
    pdf.rect(10, pdf.get_y(), 190, 22 if severity_info else 16, style="DF")
    
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(46, 117, 89)
    pdf.set_y(pdf.get_y() + 2)
    pdf.cell(0, 6, f"DIAGNOSIS: {rec_details.get('display_name', predicted_disease)}", align='C', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('helvetica', 'B', 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Confidence Score: {confidence * 100:.2f}%  |  Scientific Name: {rec_details.get('scientific_name', 'N/A')}", align='C', new_x="LMARGIN", new_y="NEXT")
    
    if severity_info:
        pdf.set_font('helvetica', 'B', 10)
        pdf.set_text_color(180, 50, 50)
        pdf.cell(0, 5, f"Estimated Disease Severity: {severity_info.get('severity_level', 'N/A')} ({severity_info.get('severity_pct', 0.0)}% surface area)", align='C', new_x="LMARGIN", new_y="NEXT")
        
    pdf.ln(6)
    
    # Images Section (Uploaded vs Grad-CAM Overlay)
    y_before_images = pdf.get_y()
    
    # Set sizes and render side-by-side
    img_width = 85
    img_height = 85
    
    if original_img_path and os.path.exists(original_img_path):
        try:
            pdf.image(original_img_path, x=15, y=y_before_images, w=img_width, h=img_height)
        except Exception as e:
            logger.error(f"Failed to render original image in PDF: {e}")
            pdf.rect(15, y_before_images, img_width, img_height)
            pdf.text(35, y_before_images + 40, "[Original Image]")
            
    if gradcam_img_path and os.path.exists(gradcam_img_path):
        try:
            pdf.image(gradcam_img_path, x=110, y=y_before_images, w=img_width, h=img_height)
        except Exception as e:
            logger.error(f"Failed to render Grad-CAM image in PDF: {e}")
            pdf.rect(110, y_before_images, img_width, img_height)
            pdf.text(130, y_before_images + 40, "[Grad-CAM Visualization]")
            
    # Move cursor past the images and reset X to left margin
    pdf.set_y(y_before_images + img_height + 4)
    pdf.set_x(10)
    
    # Captions
    pdf.set_font('helvetica', 'I', 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(95, 5, "Fig 1: Original Uploaded Image", align='C')
    pdf.cell(95, 5, "Fig 2: Grad-CAM Explainable AI Heatmap", align='C', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)
    
    # Disease details section
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(46, 117, 89)
    pdf.cell(0, 6, "1. Disease Overview", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 5, rec_details.get("description", ""), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    
    # Symptoms
    pdf.set_font('helvetica', 'B', 11)
    pdf.set_text_color(46, 117, 89)
    pdf.cell(0, 6, "Key Symptoms Identified:", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    for sym in rec_details.get("symptoms", []):
        pdf.multi_cell(0, 5, f"- {sym}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    
    # Add a page break to cleanly display controls and prevent overlap
    pdf.add_page()
    
    # Treatment and Controls
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(46, 117, 89)
    pdf.cell(0, 6, "2. Treatment & Control Recommendations", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    # Organic Controls
    pdf.set_font('helvetica', 'B', 11)
    pdf.set_text_color(120, 80, 20)  # Brownish tone
    pdf.cell(0, 6, "Organic / Biological Control Methods:", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 5, rec_details.get("treatment", {}).get("organic_control", ""), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    
    # Chemical Controls
    pdf.set_font('helvetica', 'B', 11)
    pdf.set_text_color(180, 50, 50)  # Reddish tone
    pdf.cell(0, 6, "Chemical Control Methods:", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 5, rec_details.get("treatment", {}).get("chemical_control", ""), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    
    # Recommended Compounds Table
    pdf.set_font('helvetica', 'B', 11)
    pdf.set_text_color(46, 117, 89)
    pdf.cell(0, 6, "Recommended Agricultural Products:", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    pdf.set_font('helvetica', 'B', 10)
    pdf.set_fill_color(230, 240, 235)
    pdf.cell(95, 6, "Recommended Fungicide", border=1, fill=True, align='C')
    pdf.cell(95, 6, "Recommended Insecticide/Pesticide", border=1, fill=True, align='C', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('helvetica', '', 9)
    pdf.cell(95, 8, rec_details.get("treatment", {}).get("recommended_fungicide", "N/A"), border=1, align='C')
    pdf.cell(95, 8, rec_details.get("treatment", {}).get("recommended_pesticide", "N/A"), border=1, align='C', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)
    
    # Preventive Measures
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(46, 117, 89)
    pdf.cell(0, 6, "3. Long-term Preventive Measures", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    for idx, prev in enumerate(rec_details.get("preventive_measures", [])):
        pdf.multi_cell(0, 5, f"{idx+1}. {prev}", new_x="LMARGIN", new_y="NEXT")
        
    # Save file
    try:
        pdf.output(dest_path)
        logger.info(f"PDF report successfully saved to {dest_path}")
    except Exception as e:
        logger.error(f"Error saving PDF report: {e}")
        raise e
